// /// Flutter icons PowaGroupIcon
// /// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  PowaGroupIcon
// ///      fonts:
// ///       - asset: fonts/PowaGroupIcon.ttf
// ///
// ///
// ///
// import 'package:flutter/widgets.dart';

// class PowaGroupIcon {
//   PowaGroupIcon._();

//   static const _kFontFam = 'PowaGroupIcon';
//   static const String _kFontPkg = '';

//   static const IconData group_131942 =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_131943 =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_132002 =
//       IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_132012 =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_132044 =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_132068 =
//       IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_132069 =
//       IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart =
//       IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart3 =
//       IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData live_area =
//       IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData password =
//       IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rectangle_2446 =
//       IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector =
//       IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector_1 =
//       IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cross =
//       IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData email =
//       IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filter =
//       IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_19 =
//       IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_19_1 =
//       IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData group_131934 =
//       IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add2 =
//       IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData artboard =
//       IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart =
//       IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plus =
//       IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData prefix =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home_2 =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData login =
//       IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData category_2 =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search_normal =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag_tick =
//       IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData category_1 =
//       IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eye_closed =
//       IconData(0xf366, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData add =
//       IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }

/// Flutter icons PowaGroupIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PowaGroupIcon
///      fonts:
///       - asset: fonts/PowaGroupIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PowaGroupIcon {
  PowaGroupIcon._();

  static const _kFontFam = 'PowaGroupIcon';
  static const String? _kFontPkg = null;

  static const IconData circle1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_131943 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roundslop =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menubar =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart3 =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_1 =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_2446 =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star1 =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_underscore =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_plus =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_plus_2 =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_1 =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success_1 =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
